### ISSUE TITLE
There is a spelling mistake

### ISSUE THREAD

**Issue by waterpku** [Activiti/activiti-cloud-query-service#48]
There is a spelling mistake in the first line of this file:
activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activit/cloud/services/security/SecurityPoliciesApplicationServiceTest.java

where 'activit' should be 'activiti'

**Comment by salaboy** [comment]
Thanks for reporting this.
